# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               sp0gg
#tagline:             'A Hacker like jekyll theme'
#description:         'oonlab is crafted with <3 by ariestiyansyah.'
url:                 http://sp0gg.net/blog
baseurl:             https://sp0gg.github.io/
paginate:            10

# About/contact
author:
  name:              Joe Nelson
#  url:               https://twitter.com/ariestiyansyah
  email:             blog@sp0gg.net

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
